---
title: "01_mags_quality"
date: "Compiled at `r format(Sys.time(), '%Y-%m-%d %H:%M:%S', tz = 'UTC')` UTC"
output: github_document
params:
  name: "01_mags_quality" # change if you rename file
---

```{r here, message=FALSE}
here::i_am(paste0(params$name, ".Rmd"), uuid = "03a81c7d-53d8-457f-81a1-1d4a357b635d")
```

The purpose of this document is ...

```{r packages}
library("conflicted")
library(ggplot2)
library(dplyr)
```

```{r directories}
# create or *empty* the target directory, used to write this file's data: 
projthis::proj_create_dir_target(params$name, clean = F)

# function to get path to target directory: path_target("sample.csv")
path_target <- projthis::proj_path_target(params$name)

# function to get path to previous data: path_source("00-import", "sample.csv")
path_source <- projthis::proj_path_source(params$name)
```

## Tasks

The first task is ...

## Files written

These files have been written to the target directory, ```r paste0("data/", params$name)```:

```{r list-files-target}
projthis::proj_dir_info(path_target())
```

```{r, dpi=300}
# 创建数据框
data <- data.frame(
  Category = c("Low-quality MAGs", "Medium-quality MAGs", "High-quality MAGs"),
  Count = c(977, 251, 411)
)

# 绘制饼图
ggplot(data, aes(x = "", y = Count, fill = Category)) +
  geom_bar(stat = "identity", width = 0.4) +
  coord_polar("y", start = 0) +
  geom_text(aes(label = Count), 
            position = position_stack(vjust = 0.5)) +
  labs(title = " ") +
  theme_void() +
  scale_fill_manual(values = c("red", "orange", "forestgreen")) +
  guides(fill = guide_legend(title = NULL))

data_sv_type <- data.frame(
  Category = factor(
    c("contraction", "deletion", "duplication",
      "insertion", "inversion", "transloc"),
    levels = c("contraction", "deletion", "duplication",
               "insertion", "inversion", "transloc")
  ),
  Count = c(23, 494, 44, 741, 50, 1258)
)

ggplot(data_sv_type, aes(x = "", y = Count, fill = Category)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar(theta = "y") +
  geom_text(aes(label = Count), 
            position = position_stack(vjust = 0.5), 
            size = 4) +
  scale_fill_brewer(palette = "Set3") +
  theme_void() +
  theme(legend.position = "right")  # 图例显示在右侧

```
